- hosts: build
  user: ubuntu
  become: true
  become_user: root
  vars:
    ubuntu_version: trusty
  tasks:
    - name: nodesource.com apt key
      apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

    - name: nodesource.com apt source (deb)
      apt_repository: repo='deb https://deb.nodesource.com/node_6.x {{ ubuntu_version }} main' state=present

    - name: nodesource.com apt source (deb-src)
      apt_repository: repo='deb-src https://deb.nodesource.com/node_6.x {{ ubuntu_version }} main' state=present

    - name: erlang solutions
      apt: deb=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb

    - name: apt-get update
      apt: update_cache=yes

    - name: install esl-erlang
      apt: pkg=esl-erlang=1:19.0 state=present

    - name: install elixir
      apt: pkg=elixir=1.3.1-1 state=present

    - name: install nodejs
      apt: pkg=nodejs=6.3.0-1nodesource1~trusty1 state=present

    - name: updating hex
      shell: mix local.hex --force
      args:
        creates: /home/ubuntu/.mix/archives/hex-0.12.1

    - name: updating rebar
      shell: mix local.rebar --force
      args:
        creates: /home/ubuntu/.mix/rebar

- hosts: webservers
  user: ubuntu
  become: true
  become_user: root
  vars:
    ubuntu_version: trusty
  tasks:
    - name: create user
      user: name=deployer shell=/bin/bash

    - name: mkdir .ssh
      file: path=/home/deployer/.ssh state=directory owner=deployer

    - name: copy .ssh/authorized_keys
      copy: src=./files/ssh-authorized-keys dest=/home/deployer/.ssh/authorized_keys owner=deployer mode=600

    - name: make /opt/app
      file: path=/opt/app state=directory owner=deployer
